In [1]:
from pathlib import Path
import numpy as np
import pandas as pd

from rdkit import RDLogger
RDLogger.DisableLog('rdApp.*')

In [2]:
ocr_dir = Path("results/mol_rep_ocr/v1.1/ablation_num_train_epoch")
conversion_dir = Path("results/mol_rep_conversion/v1.1/ablation_num_train_epoch")

## OCR

In [3]:
ocr_raw_reponses = pd.DataFrame()

for file in (ocr_dir / "raw_responses").glob("*.jsonl"):
    df = pd.read_json(file, lines=True)
    ocr_raw_reponses = pd.concat([ocr_raw_reponses, df], axis=0, ignore_index=True)

In [4]:
from src.utils import compute_mol_metrics

ocr_df = ocr_raw_reponses.copy()

ocr_df[['is_gt_valid', 'is_pred_valid', 'is_em', 'is_can_smiles_match', 'is_inchikey_match', 'tanimoto_sim', '_parse_status']] = ocr_raw_reponses.apply(lambda row: compute_mol_metrics(row["completion"], row["raw_responses"], row["output_rep_type"]), axis=1, result_type="expand")

In [5]:
def aggregate_func(df):
    return pd.Series({
        "num_samples": df.shape[0],
        "gt_valid_ratio": df["is_gt_valid"].mean(),
        "pred_valid_ratio": df["is_pred_valid"].mean(),
        "em_ratio": df["is_em"].mean(),
        "can_smiles_match_ratio": df["is_can_smiles_match"].mean(),
        "inchikey_match_ratio": df["is_inchikey_match"].mean(),
        "tanimoto_sim_mean": df["tanimoto_sim"].mean(),
        "tanimoto_sim_std": df["tanimoto_sim"].std(),
    })

In [6]:
ocr_df.groupby(["model_name", "num_train_epoch"]).apply(aggregate_func).to_csv(ocr_dir / "metrics_overall.csv")
ocr_df.groupby(["model_name", "num_train_epoch"]).apply(aggregate_func)

                                                                    num_samples  \
model_name                                         num_train_epoch
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                       80.0
                                                   2                       80.0
                                                   3                       80.0
                                                   4                       80.0
                                                   5                       80.0
                                                   6                       80.0
                                                   7                       80.0
qwen3_vl_4b_i_sft_lora_conversion                  1                       80.0
                                                   2                       80.0
                                                   3                       80.0
                                                   4                       80.0
                                                   5                       80.0
                                                   6                       80.0
                                                   7                       80.0
                                                   8                       80.0
                                                   9                       80.0
                                                   10                      80.0
qwen3_vl_4b_i_sft_lora_ocr                         1                       80.0
                                                   2                       80.0
                                                   3                       80.0
                                                   4                       80.0
                                                   5                       80.0
                                                   6                       80.0
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                       80.0
                                                   2                       80.0
                                                   3                       80.0
                                                   4                       80.0
                                                   5                       80.0
                                                   6                       80.0
                                                   7                       80.0
                                                   8                       80.0
                                                   9                       80.0
                                                   10                      80.0

                                                                    gt_valid_ratio  \
model_name                                         num_train_epoch
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                           1.0
                                                   2                           1.0
                                                   3                           1.0
                                                   4                           1.0
                                                   5                           1.0
                                                   6                           1.0
                                                   7                           1.0
qwen3_vl_4b_i_sft_lora_conversion                  1                           1.0
                                                   2                           1.0
                                                   3                           1.0
                                                   4                           1.0
                                                   5                           1.0
                                                   6                           1.0
                                                   7                           1.0
                                                   8                           1.0
                                                   9                           1.0
                                                   10                          1.0
qwen3_vl_4b_i_sft_lora_ocr                         1                           1.0
                                                   2                           1.0
                                                   3                           1.0
                                                   4                           1.0
                                                   5                           1.0
                                                   6                           1.0
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                           1.0
                                                   2                           1.0
                                                   3                           1.0
                                                   4                           1.0
                                                   5                           1.0
                                                   6                           1.0
                                                   7                           1.0
                                                   8                           1.0
                                                   9                           1.0
                                                   10                          1.0

                                                                    pred_valid_ratio  \
model_name                                         num_train_epoch
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                          0.6750
                                                   2                          0.7000
                                                   3                          0.6875
                                                   4                          0.6750
                                                   5                          0.7000
                                                   6                          0.7000
                                                   7                          0.6750
qwen3_vl_4b_i_sft_lora_conversion                  1                          0.5250
                                                   2                          0.5750
                                                   3                          0.5750
                                                   4                          0.6125
                                                   5                          0.6375
                                                   6                          0.6000
                                                   7                          0.6875
                                                   8                          0.6375
                                                   9                          0.6750
                                                   10                         0.6750
qwen3_vl_4b_i_sft_lora_ocr                         1                          0.2250
                                                   2                          0.2250
                                                   3                          0.3250
                                                   4                          0.4375
                                                   5                          0.3875
                                                   6                          0.4125
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                          0.5000
                                                   2                          0.5375
                                                   3                          0.5625
                                                   4                          0.6000
                                                   5                          0.6000
                                                   6                          0.6375
                                                   7                          0.6250
                                                   8                          0.6750
                                                   9                          0.6750
                                                   10                         0.6750

                                                                    em_ratio  \
model_name                                         num_train_epoch
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                  0.2625
                                                   2                  0.2750
                                                   3                  0.2500
                                                   4                  0.2375
                                                   5                  0.2500
                                                   6                  0.2500
                                                   7                  0.2750
qwen3_vl_4b_i_sft_lora_conversion                  1                  0.0375
                                                   2                  0.0750
                                                   3                  0.1125
                                                   4                  0.1875
                                                   5                  0.1750
                                                   6                  0.2125
                                                   7                  0.2250
                                                   8                  0.2000
                                                   9                  0.2125
                                                   10                 0.2250
qwen3_vl_4b_i_sft_lora_ocr                         1                  0.0125
                                                   2                  0.0125
                                                   3                  0.0250
                                                   4                  0.0375
                                                   5                  0.0375
                                                   6                  0.0375
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                  0.0500
                                                   2                  0.1125
                                                   3                  0.1250
                                                   4                  0.2500
                                                   5                  0.2000
                                                   6                  0.2250
                                                   7                  0.2750
                                                   8                  0.2625
                                                   9                  0.2375
                                                   10                 0.2625

                                                                    can_smiles_match_ratio  \
model_name                                         num_train_epoch
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                                0.2625
                                                   2                                0.2750
                                                   3                                0.2500
                                                   4                                0.2375
                                                   5                                0.2500
                                                   6                                0.2500
                                                   7                                0.2750
qwen3_vl_4b_i_sft_lora_conversion                  1                                0.0375
                                                   2                                0.0750
                                                   3                                0.1125
                                                   4                                0.1875
                                                   5                                0.1750
                                                   6                                0.2125
                                                   7                                0.2250
                                                   8                                0.2000
                                                   9                                0.2125
                                                   10                               0.2250
qwen3_vl_4b_i_sft_lora_ocr                         1                                0.0125
                                                   2                                0.0250
                                                   3                                0.0250
                                                   4                                0.0375
                                                   5                                0.0375
                                                   6                                0.0375
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                                0.0500
                                                   2                                0.1125
                                                   3                                0.1250
                                                   4                                0.2500
                                                   5                                0.2000
                                                   6                                0.2250
                                                   7                                0.2750
                                                   8                                0.2625
                                                   9                                0.2375
                                                   10                               0.2625

                                                                    inchikey_match_ratio  \
model_name                                         num_train_epoch
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                              0.2625
                                                   2                              0.2750
                                                   3                              0.2500
                                                   4                              0.2375
                                                   5                              0.2500
                                                   6                              0.2500
                                                   7                              0.2750
qwen3_vl_4b_i_sft_lora_conversion                  1                              0.0375
                                                   2                              0.0750
                                                   3                              0.1125
                                                   4                              0.1875
                                                   5                              0.1750
                                                   6                              0.2125
                                                   7                              0.2250
                                                   8                              0.2000
                                                   9                              0.2125
                                                   10                             0.2250
qwen3_vl_4b_i_sft_lora_ocr                         1                              0.0125
                                                   2                              0.0250
                                                   3                              0.0375
                                                   4                              0.0375
                                                   5                              0.0375
                                                   6                              0.0500
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                              0.0500
                                                   2                              0.1125
                                                   3                              0.1250
                                                   4                              0.2500
                                                   5                              0.2000
                                                   6                              0.2250
                                                   7                              0.2750
                                                   8                              0.2625
                                                   9                              0.2375
                                                   10                             0.2625

                                                                    tanimoto_sim_mean  \
model_name                                         num_train_epoch
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                         0.392437
                                                   2                         0.422592
                                                   3                         0.399270
                                                   4                         0.402736
                                                   5                         0.408629
                                                   6                         0.415847
                                                   7                         0.412436
qwen3_vl_4b_i_sft_lora_conversion                  1                         0.161916
                                                   2                         0.227057
                                                   3                         0.235306
                                                   4                         0.317823
                                                   5                         0.325174
                                                   6                         0.334632
                                                   7                         0.359032
                                                   8                         0.335076
                                                   9                         0.343160
                                                   10                        0.353959
qwen3_vl_4b_i_sft_lora_ocr                         1                         0.070293
                                                   2                         0.066791
                                                   3                         0.110265
                                                   4                         0.173264
                                                   5                         0.127524
                                                   6                         0.146852
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                         0.200549
                                                   2                         0.248344
                                                   3                         0.266565

In [7]:
# ocr_df.groupby("_parse_status").apply(aggregate_func).to_csv(ocr_dir / "metrics_by_parse_status.csv")
ocr_df[ocr_df._parse_status == "success"].groupby(["model_name", "num_train_epoch"]).apply(aggregate_func)

                                                                    num_samples  \
model_name                                         num_train_epoch
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                       54.0
                                                   2                       56.0
                                                   3                       55.0
                                                   4                       54.0
                                                   5                       56.0
                                                   6                       56.0
                                                   7                       54.0
qwen3_vl_4b_i_sft_lora_conversion                  1                       42.0
                                                   2                       46.0
                                                   3                       46.0
                                                   4                       49.0
                                                   5                       51.0
                                                   6                       48.0
                                                   7                       55.0
                                                   8                       51.0
                                                   9                       54.0
                                                   10                      54.0
qwen3_vl_4b_i_sft_lora_ocr                         1                       18.0
                                                   2                       18.0
                                                   3                       26.0
                                                   4                       35.0
                                                   5                       31.0
                                                   6                       33.0
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                       40.0
                                                   2                       43.0
                                                   3                       45.0
                                                   4                       48.0
                                                   5                       48.0
                                                   6                       51.0
                                                   7                       50.0
                                                   8                       54.0
                                                   9                       54.0
                                                   10                      54.0

                                                                    gt_valid_ratio  \
model_name                                         num_train_epoch
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                           1.0
                                                   2                           1.0
                                                   3                           1.0
                                                   4                           1.0
                                                   5                           1.0
                                                   6                           1.0
                                                   7                           1.0
qwen3_vl_4b_i_sft_lora_conversion                  1                           1.0
                                                   2                           1.0
                                                   3                           1.0
                                                   4                           1.0
                                                   5                           1.0
                                                   6                           1.0
                                                   7                           1.0
                                                   8                           1.0
                                                   9                           1.0
                                                   10                          1.0
qwen3_vl_4b_i_sft_lora_ocr                         1                           1.0
                                                   2                           1.0
                                                   3                           1.0
                                                   4                           1.0
                                                   5                           1.0
                                                   6                           1.0
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                           1.0
                                                   2                           1.0
                                                   3                           1.0
                                                   4                           1.0
                                                   5                           1.0
                                                   6                           1.0
                                                   7                           1.0
                                                   8                           1.0
                                                   9                           1.0
                                                   10                          1.0

                                                                    pred_valid_ratio  \
model_name                                         num_train_epoch
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                             1.0
                                                   2                             1.0
                                                   3                             1.0
                                                   4                             1.0
                                                   5                             1.0
                                                   6                             1.0
                                                   7                             1.0
qwen3_vl_4b_i_sft_lora_conversion                  1                             1.0
                                                   2                             1.0
                                                   3                             1.0
                                                   4                             1.0
                                                   5                             1.0
                                                   6                             1.0
                                                   7                             1.0
                                                   8                             1.0
                                                   9                             1.0
                                                   10                            1.0
qwen3_vl_4b_i_sft_lora_ocr                         1                             1.0
                                                   2                             1.0
                                                   3                             1.0
                                                   4                             1.0
                                                   5                             1.0
                                                   6                             1.0
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                             1.0
                                                   2                             1.0
                                                   3                             1.0
                                                   4                             1.0
                                                   5                             1.0
                                                   6                             1.0
                                                   7                             1.0
                                                   8                             1.0
                                                   9                             1.0
                                                   10                            1.0

                                                                    em_ratio  \
model_name                                         num_train_epoch
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                0.388889
                                                   2                0.392857
                                                   3                0.363636
                                                   4                0.351852
                                                   5                0.357143
                                                   6                0.357143
                                                   7                0.407407
qwen3_vl_4b_i_sft_lora_conversion                  1                0.071429
                                                   2                0.130435
                                                   3                0.195652
                                                   4                0.306122
                                                   5                0.274510
                                                   6                0.354167
                                                   7                0.327273
                                                   8                0.313725
                                                   9                0.314815
                                                   10               0.333333
qwen3_vl_4b_i_sft_lora_ocr                         1                0.055556
                                                   2                0.055556
                                                   3                0.076923
                                                   4                0.085714
                                                   5                0.096774
                                                   6                0.090909
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                0.100000
                                                   2                0.209302
                                                   3                0.222222
                                                   4                0.416667
                                                   5                0.333333
                                                   6                0.352941
                                                   7                0.440000
                                                   8                0.388889
                                                   9                0.351852
                                                   10               0.388889

                                                                    can_smiles_match_ratio  \
model_name                                         num_train_epoch
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                              0.388889
                                                   2                              0.392857
                                                   3                              0.363636
                                                   4                              0.351852
                                                   5                              0.357143
                                                   6                              0.357143
                                                   7                              0.407407
qwen3_vl_4b_i_sft_lora_conversion                  1                              0.071429
                                                   2                              0.130435
                                                   3                              0.195652
                                                   4                              0.306122
                                                   5                              0.274510
                                                   6                              0.354167
                                                   7                              0.327273
                                                   8                              0.313725
                                                   9                              0.314815
                                                   10                             0.333333
qwen3_vl_4b_i_sft_lora_ocr                         1                              0.055556
                                                   2                              0.111111
                                                   3                              0.076923
                                                   4                              0.085714
                                                   5                              0.096774
                                                   6                              0.090909
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                              0.100000
                                                   2                              0.209302
                                                   3                              0.222222
                                                   4                              0.416667
                                                   5                              0.333333
                                                   6                              0.352941
                                                   7                              0.440000
                                                   8                              0.388889
                                                   9                              0.351852
                                                   10                             0.388889

                                                                    inchikey_match_ratio  \
model_name                                         num_train_epoch
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                            0.388889
                                                   2                            0.392857
                                                   3                            0.363636
                                                   4                            0.351852
                                                   5                            0.357143
                                                   6                            0.357143
                                                   7                            0.407407
qwen3_vl_4b_i_sft_lora_conversion                  1                            0.071429
                                                   2                            0.130435
                                                   3                            0.195652
                                                   4                            0.306122
                                                   5                            0.274510
                                                   6                            0.354167
                                                   7                            0.327273
                                                   8                            0.313725
                                                   9                            0.314815
                                                   10                           0.333333
qwen3_vl_4b_i_sft_lora_ocr                         1                            0.055556
                                                   2                            0.111111
                                                   3                            0.115385
                                                   4                            0.085714
                                                   5                            0.096774
                                                   6                            0.121212
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                            0.100000
                                                   2                            0.209302
                                                   3                            0.222222
                                                   4                            0.416667
                                                   5                            0.333333
                                                   6                            0.352941
                                                   7                            0.440000
                                                   8                            0.388889
                                                   9                            0.351852
                                                   10                           0.388889

                                                                    tanimoto_sim_mean  \
model_name                                         num_train_epoch
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                         0.581389
                                                   2                         0.603702
                                                   3                         0.580757
                                                   4                         0.596645
                                                   5                         0.583756
                                                   6                         0.594067
                                                   7                         0.611016
qwen3_vl_4b_i_sft_lora_conversion                  1                         0.308412
                                                   2                         0.394882
                                                   3                         0.409228
                                                   4                         0.518895
                                                   5                         0.510077
                                                   6                         0.557720
                                                   7                         0.522228
                                                   8                         0.525610
                                                   9                         0.508385
                                                   10                        0.524383
qwen3_vl_4b_i_sft_lora_ocr                         1                         0.312415
                                                   2                         0.296851
                                                   3                         0.339278
                                                   4                         0.396032
                                                   5                         0.329093
                                                   6                         0.356005
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                         0.401098
                                                   2                         0.462035
                                                   3                         0.473893

## Conversion

In [8]:
conversion_raw_reponses = pd.DataFrame()

for file in (conversion_dir / "raw_responses").glob("*.jsonl"):
    df = pd.read_json(file, lines=True)
    conversion_raw_reponses = pd.concat([conversion_raw_reponses, df], axis=0, ignore_index=True)

In [9]:
conversion_df = conversion_raw_reponses.copy()

conversion_df[['is_gt_valid', 'is_pred_valid', 'is_em', 'is_can_smiles_match', 'is_inchikey_match', 'tanimoto_sim', '_parse_status']] = conversion_raw_reponses.apply(lambda row: compute_mol_metrics(row["completion"], row["raw_responses"], row["output_rep_type"]), axis=1, result_type="expand")

In [10]:
conversion_df.groupby(["model_name", "num_train_epoch"]).apply(aggregate_func).to_csv(conversion_dir / "metrics_overall.csv")
conversion_df.groupby(["model_name", "num_train_epoch"]).apply(aggregate_func)

                                                                    num_samples  \
model_name                                         num_train_epoch
qwen3_4b_i_sft_lora_conversion                     1                      875.0
                                                   2                      875.0
                                                   3                      875.0
                                                   4                      875.0
                                                   5                      875.0
                                                   6                      875.0
                                                   7                      875.0
                                                   8                      875.0
                                                   9                      875.0
                                                   10                     875.0
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                      875.0
                                                   2                      875.0
                                                   3                      875.0
                                                   4                      875.0
                                                   5                      875.0
                                                   6                      875.0
                                                   7                      875.0
qwen3_vl_4b_i_sft_lora_conversion                  1                      875.0
                                                   2                      875.0
                                                   3                      875.0
                                                   4                      875.0
                                                   5                      875.0
                                                   6                      875.0
                                                   7                      875.0
                                                   8                      875.0
                                                   9                      875.0
                                                   10                     875.0
qwen3_vl_4b_i_sft_lora_ocr                         1                      875.0
                                                   2                      875.0
                                                   3                      875.0
                                                   4                      875.0
                                                   5                      875.0
                                                   6                      875.0
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                      875.0
                                                   2                      875.0
                                                   3                      875.0
                                                   4                      875.0
                                                   5                      875.0
                                                   6                      875.0
                                                   7                      875.0
                                                   8                      875.0
                                                   9                      875.0
                                                   10                     875.0

                                                                    gt_valid_ratio  \
model_name                                         num_train_epoch
qwen3_4b_i_sft_lora_conversion                     1                           1.0
                                                   2                           1.0
                                                   3                           1.0
                                                   4                           1.0
                                                   5                           1.0
                                                   6                           1.0
                                                   7                           1.0
                                                   8                           1.0
                                                   9                           1.0
                                                   10                          1.0
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                           1.0
                                                   2                           1.0
                                                   3                           1.0
                                                   4                           1.0
                                                   5                           1.0
                                                   6                           1.0
                                                   7                           1.0
qwen3_vl_4b_i_sft_lora_conversion                  1                           1.0
                                                   2                           1.0
                                                   3                           1.0
                                                   4                           1.0
                                                   5                           1.0
                                                   6                           1.0
                                                   7                           1.0
                                                   8                           1.0
                                                   9                           1.0
                                                   10                          1.0
qwen3_vl_4b_i_sft_lora_ocr                         1                           1.0
                                                   2                           1.0
                                                   3                           1.0
                                                   4                           1.0
                                                   5                           1.0
                                                   6                           1.0
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                           1.0
                                                   2                           1.0
                                                   3                           1.0
                                                   4                           1.0
                                                   5                           1.0
                                                   6                           1.0
                                                   7                           1.0
                                                   8                           1.0
                                                   9                           1.0
                                                   10                          1.0

                                                                    pred_valid_ratio  \
model_name                                         num_train_epoch
qwen3_4b_i_sft_lora_conversion                     1                        0.390857
                                                   2                        0.483429
                                                   3                        0.596571
                                                   4                        0.651429
                                                   5                        0.760000
                                                   6                        0.833143
                                                   7                        0.865143
                                                   8                        0.876571
                                                   9                        0.904000
                                                   10                       0.901714
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                        0.910857
                                                   2                        0.912000
                                                   3                        0.908571
                                                   4                        0.902857
                                                   5                        0.904000
                                                   6                        0.906286
                                                   7                        0.907429
qwen3_vl_4b_i_sft_lora_conversion                  1                        0.464000
                                                   2                        0.536000
                                                   3                        0.626286
                                                   4                        0.699429
                                                   5                        0.766857
                                                   6                        0.801143
                                                   7                        0.867429
                                                   8                        0.898286
                                                   9                        0.899429
                                                   10                       0.898286
qwen3_vl_4b_i_sft_lora_ocr                         1                        0.184000
                                                   2                        0.180571
                                                   3                        0.218286
                                                   4                        0.248000
                                                   5                        0.238857
                                                   6                        0.224000
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                        0.489143
                                                   2                        0.555429
                                                   3                        0.635429
                                                   4                        0.737143
                                                   5                        0.778286
                                                   6                        0.838857
                                                   7                        0.892571
                                                   8                        0.883429
                                                   9                        0.905143
                                                   10                       0.916571

                                                                    em_ratio  \
model_name                                         num_train_epoch
qwen3_4b_i_sft_lora_conversion                     1                0.036571
                                                   2                0.100571
                                                   3                0.253714
                                                   4                0.369143
                                                   5                0.492571
                                                   6                0.612571
                                                   7                0.664000
                                                   8                0.701714
                                                   9                0.747429
                                                   10               0.746286
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                0.730286
                                                   2                0.736000
                                                   3                0.725714
                                                   4                0.734857
                                                   5                0.722286
                                                   6                0.728000
                                                   7                0.729143
qwen3_vl_4b_i_sft_lora_conversion                  1                0.068571
                                                   2                0.164571
                                                   3                0.288000
                                                   4                0.419429
                                                   5                0.513143
                                                   6                0.579429
                                                   7                0.664000
                                                   8                0.717714
                                                   9                0.722286
                                                   10               0.726857
qwen3_vl_4b_i_sft_lora_ocr                         1                0.000000
                                                   2                0.000000
                                                   3                0.000000
                                                   4                0.000000
                                                   5                0.000000
                                                   6                0.001143
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                0.068571
                                                   2                0.194286
                                                   3                0.308571
                                                   4                0.453714
                                                   5                0.522286
                                                   6                0.606857
                                                   7                0.682286
                                                   8                0.692571
                                                   9                0.718857
                                                   10               0.734857

                                                                    can_smiles_match_ratio  \
model_name                                         num_train_epoch
qwen3_4b_i_sft_lora_conversion                     1                              0.038857
                                                   2                              0.102857
                                                   3                              0.254857
                                                   4                              0.370286
                                                   5                              0.492571
                                                   6                              0.612571
                                                   7                              0.664000
                                                   8                              0.701714
                                                   9                              0.747429
                                                   10                             0.746286
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                              0.730286
                                                   2                              0.736000
                                                   3                              0.725714
                                                   4                              0.734857
                                                   5                              0.722286
                                                   6                              0.728000
                                                   7                              0.729143
qwen3_vl_4b_i_sft_lora_conversion                  1                              0.069714
                                                   2                              0.164571
                                                   3                              0.288000
                                                   4                              0.421714
                                                   5                              0.513143
                                                   6                              0.579429
                                                   7                              0.664000
                                                   8                              0.717714
                                                   9                              0.722286
                                                   10                             0.726857
qwen3_vl_4b_i_sft_lora_ocr                         1                              0.058286
                                                   2                              0.057143
                                                   3                              0.056000
                                                   4                              0.049143
                                                   5                              0.044571
                                                   6                              0.040000
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                              0.068571
                                                   2                              0.195429
                                                   3                              0.308571
                                                   4                              0.453714
                                                   5                              0.523429
                                                   6                              0.606857
                                                   7                              0.682286
                                                   8                              0.692571
                                                   9                              0.718857
                                                   10                             0.734857

                                                                    inchikey_match_ratio  \
model_name                                         num_train_epoch
qwen3_4b_i_sft_lora_conversion                     1                            0.038857
                                                   2                            0.104000
                                                   3                            0.256000
                                                   4                            0.370286
                                                   5                            0.492571
                                                   6                            0.612571
                                                   7                            0.664000
                                                   8                            0.701714
                                                   9                            0.747429
                                                   10                           0.746286
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                            0.730286
                                                   2                            0.736000
                                                   3                            0.725714

In [11]:
# conversion_df.groupby("_parse_status").apply(aggregate_func).to_csv(conversion_dir / "metrics_by_parse_status.csv")
conversion_df[conversion_df._parse_status == "success"].groupby(["model_name", "num_train_epoch"]).apply(aggregate_func)

                                                                    num_samples  \
model_name                                         num_train_epoch
qwen3_4b_i_sft_lora_conversion                     1                      342.0
                                                   2                      423.0
                                                   3                      522.0
                                                   4                      570.0
                                                   5                      665.0
                                                   6                      729.0
                                                   7                      757.0
                                                   8                      767.0
                                                   9                      791.0
                                                   10                     789.0
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                      797.0
                                                   2                      798.0
                                                   3                      795.0
                                                   4                      790.0
                                                   5                      791.0
                                                   6                      793.0
                                                   7                      794.0
qwen3_vl_4b_i_sft_lora_conversion                  1                      406.0
                                                   2                      469.0
                                                   3                      548.0
                                                   4                      612.0
                                                   5                      671.0
                                                   6                      701.0
                                                   7                      759.0
                                                   8                      786.0
                                                   9                      787.0
                                                   10                     786.0
qwen3_vl_4b_i_sft_lora_ocr                         1                      161.0
                                                   2                      158.0
                                                   3                      191.0
                                                   4                      217.0
                                                   5                      209.0
                                                   6                      196.0
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                      428.0
                                                   2                      486.0
                                                   3                      556.0
                                                   4                      645.0
                                                   5                      681.0
                                                   6                      734.0
                                                   7                      781.0
                                                   8                      773.0
                                                   9                      792.0
                                                   10                     802.0

                                                                    gt_valid_ratio  \
model_name                                         num_train_epoch
qwen3_4b_i_sft_lora_conversion                     1                           1.0
                                                   2                           1.0
                                                   3                           1.0
                                                   4                           1.0
                                                   5                           1.0
                                                   6                           1.0
                                                   7                           1.0
                                                   8                           1.0
                                                   9                           1.0
                                                   10                          1.0
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                           1.0
                                                   2                           1.0
                                                   3                           1.0
                                                   4                           1.0
                                                   5                           1.0
                                                   6                           1.0
                                                   7                           1.0
qwen3_vl_4b_i_sft_lora_conversion                  1                           1.0
                                                   2                           1.0
                                                   3                           1.0
                                                   4                           1.0
                                                   5                           1.0
                                                   6                           1.0
                                                   7                           1.0
                                                   8                           1.0
                                                   9                           1.0
                                                   10                          1.0
qwen3_vl_4b_i_sft_lora_ocr                         1                           1.0
                                                   2                           1.0
                                                   3                           1.0
                                                   4                           1.0
                                                   5                           1.0
                                                   6                           1.0
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                           1.0
                                                   2                           1.0
                                                   3                           1.0
                                                   4                           1.0
                                                   5                           1.0
                                                   6                           1.0
                                                   7                           1.0
                                                   8                           1.0
                                                   9                           1.0
                                                   10                          1.0

                                                                    pred_valid_ratio  \
model_name                                         num_train_epoch
qwen3_4b_i_sft_lora_conversion                     1                             1.0
                                                   2                             1.0
                                                   3                             1.0
                                                   4                             1.0
                                                   5                             1.0
                                                   6                             1.0
                                                   7                             1.0
                                                   8                             1.0
                                                   9                             1.0
                                                   10                            1.0
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                             1.0
                                                   2                             1.0
                                                   3                             1.0
                                                   4                             1.0
                                                   5                             1.0
                                                   6                             1.0
                                                   7                             1.0
qwen3_vl_4b_i_sft_lora_conversion                  1                             1.0
                                                   2                             1.0
                                                   3                             1.0
                                                   4                             1.0
                                                   5                             1.0
                                                   6                             1.0
                                                   7                             1.0
                                                   8                             1.0
                                                   9                             1.0
                                                   10                            1.0
qwen3_vl_4b_i_sft_lora_ocr                         1                             1.0
                                                   2                             1.0
                                                   3                             1.0
                                                   4                             1.0
                                                   5                             1.0
                                                   6                             1.0
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                             1.0
                                                   2                             1.0
                                                   3                             1.0
                                                   4                             1.0
                                                   5                             1.0
                                                   6                             1.0
                                                   7                             1.0
                                                   8                             1.0
                                                   9                             1.0
                                                   10                            1.0

                                                                    em_ratio  \
model_name                                         num_train_epoch
qwen3_4b_i_sft_lora_conversion                     1                0.093567
                                                   2                0.208038
                                                   3                0.425287
                                                   4                0.566667
                                                   5                0.648120
                                                   6                0.735254
                                                   7                0.767503
                                                   8                0.800522
                                                   9                0.826802
                                                   10               0.827630
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                0.801757
                                                   2                0.807018
                                                   3                0.798742
                                                   4                0.813924
                                                   5                0.798989
                                                   6                0.803279
                                                   7                0.803526
qwen3_vl_4b_i_sft_lora_conversion                  1                0.147783
                                                   2                0.307036
                                                   3                0.459854
                                                   4                0.599673
                                                   5                0.669151
                                                   6                0.723252
                                                   7                0.765481
                                                   8                0.798982
                                                   9                0.803050
                                                   10               0.809160
qwen3_vl_4b_i_sft_lora_ocr                         1                0.000000
                                                   2                0.000000
                                                   3                0.000000
                                                   4                0.000000
                                                   5                0.000000
                                                   6                0.005102
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                0.140187
                                                   2                0.349794
                                                   3                0.485612
                                                   4                0.615504
                                                   5                0.671072
                                                   6                0.723433
                                                   7                0.764405
                                                   8                0.783959
                                                   9                0.794192
                                                   10               0.801746

                                                                    can_smiles_match_ratio  \
model_name                                         num_train_epoch
qwen3_4b_i_sft_lora_conversion                     1                              0.099415
                                                   2                              0.212766
                                                   3                              0.427203
                                                   4                              0.568421
                                                   5                              0.648120
                                                   6                              0.735254
                                                   7                              0.767503
                                                   8                              0.800522
                                                   9                              0.826802
                                                   10                             0.827630
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                              0.801757
                                                   2                              0.807018
                                                   3                              0.798742
                                                   4                              0.813924
                                                   5                              0.798989
                                                   6                              0.803279
                                                   7                              0.803526
qwen3_vl_4b_i_sft_lora_conversion                  1                              0.150246
                                                   2                              0.307036
                                                   3                              0.459854
                                                   4                              0.602941
                                                   5                              0.669151
                                                   6                              0.723252
                                                   7                              0.765481
                                                   8                              0.798982
                                                   9                              0.803050
                                                   10                             0.809160
qwen3_vl_4b_i_sft_lora_ocr                         1                              0.316770
                                                   2                              0.316456
                                                   3                              0.256545
                                                   4                              0.198157
                                                   5                              0.186603
                                                   6                              0.178571
qwen3_vl_4b_i_sft_lora_ocr_conversion              1                              0.140187
                                                   2                              0.351852
                                                   3                              0.485612
                                                   4                              0.615504
                                                   5                              0.672540
                                                   6                              0.723433
                                                   7                              0.764405
                                                   8                              0.783959
                                                   9                              0.794192
                                                   10                             0.801746

                                                                    inchikey_match_ratio  \
model_name                                         num_train_epoch
qwen3_4b_i_sft_lora_conversion                     1                            0.099415
                                                   2                            0.215130
                                                   3                            0.429119
                                                   4                            0.568421
                                                   5                            0.648120
                                                   6                            0.735254
                                                   7                            0.767503
                                                   8                            0.800522
                                                   9                            0.826802
                                                   10                           0.827630
qwen3_vl_4b_i_grpo_lora_from_sft_lora_ocr_conve... 1                            0.801757
                                                   2                            0.807018
                                                   3                            0.798742

In [12]:
# conversion_df.groupby(["output_rep_type"]).apply(aggregate_func).to_csv(conversion_dir / "metrics_by_output_rep_type.csv")
# conversion_df.groupby(["model_name", "output_rep_type"]).apply(aggregate_func)

In [13]:
# conversion_df.groupby(["input_rep_type"]).apply(aggregate_func)

In [14]:
# conversion_df.groupby(["task_type"]).apply(aggregate_func).to_csv(conversion_dir / "metrics_by_task_type.csv")
# conversion_df.groupby(["model_name", "task_type"]).apply(aggregate_func)

In [15]:
# conversion_df.groupby(["model_name", "task_id"]).apply(aggregate_func)